# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
          Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user@example.com:
                        password: user1
                        roles: 'ROLE_USER'
                    root@example.com:
                        password: root1
                        roles: ['ROLE_ADMIN', 'ROLE_USER']

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            methods: [GET, POST, DELETE, PUT]

            form_login:
                username_parameter: email
                password_parameter: password
                check_path: login_check
                always_use_default_target_path: false
                default_target_path: login_success
                failure_path: login_failure
                failure_forward: true
                remember_me: true
            logout:
                path: logout
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:      [ROLE_USER]
        ROLE_SUPERADMIN: [ROLE_ADMIN]

